# Sheldon plugin configuration
# See: https://sheldon.cli.rs/

shell = "zsh"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"

[plugins.zsh-you-should-use]
github = "MichaelAquilina/zsh-you-should-use"

[plugins.starship]
inline = 'eval "$(starship init zsh)"'
