# Sheldon plugin configuration
# See: https://sheldon.cli.rs/

shell = "zsh"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.starship]
inline = 'eval "$(starship init zsh)"'
