# Starship configuration
# See: https://starship.rs/

# Single-line display format
format = """
$directory\
$git_branch\
$git_status\
$kubernetes\
$character
"""

# Do not add newline
add_newline = false

[directory]
truncation_length = 0
truncate_to_repo = false
home_symbol = "~"
format = "[$path]($style) "
style = "#808080"
read_only = " "

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "green"
truncation_length = 20
truncation_symbol = "â€¦"

[git_status]
format = '([$all_status$ahead_behind]($style) )'
style = "yellow"
conflicted = "ðŸ³"
ahead = "â‡¡${count}"
behind = "â‡£${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
untracked = "?"
stashed = "$"
modified = "!"
staged = "+"
renamed = "Â»"
deleted = "âœ˜"

[kubernetes]
disabled = false
format = '[\($context:$namespace\)]($style) '
style = "cyan"

[character]
success_symbol = "[>](white)"
error_symbol = "[>](bold red)"
vimcmd_symbol = "[<](bold green)"
